### PR TITLE
Rebase on upstream to 0.2.0

### PR DESCRIPTION
**Pull request by IanVS**
Hi, 

This is my attempt to help get this fork up-to-date with `@storybook/builder-vite`, but I think I didn't do it correctly.  I did a `git rebase`, but I probably wanted to go the other direction.  So, I'm not sure if you can merge this, and I'm not really sure the best way to make it mergable.  I also probably didn't do a super-clean rebase, so some of the commits won't really make as much sense anymore.  

This fork has diverged more than I expected from the upstream, so it was a bit more work than I thought it'd be, but maybe something here is useful.

### CODE REVIEW

**Comment by Djaler** [comment]
Hi. I used to `merge` upstream instead of `rebase` and solve all conflicts in merge commit

**Comment by Djaler** [comment]
BTW I need to try to add vue 2 support into upstream repo. I have tried once, but there were some problems because of two different versions of vue in monorepo

**Comment by IanVS** [comment]
I'd consider accepting such a PR into `@storybook/builder-vite` if it doesn't seem to add much complication or cause problems.  I can't imagine that maintaining this fork is much fun, given the pace of changes upstream.

**Comment by Djaler** [comment]
Yeah, as you can see, I quickly gave up from updating it :)

**Pull request closed without merging**
